version: '3.8'

networks:
  api:
  db:


services:
  db:
    image: postgres:latest
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - db
      - api
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: test-verse:58
    restart: always
    networks:
      - api
      - db
    ports:
      - '3001:3001'
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
